[tool.poetry]
name = "heredity"
version = "0.1.0"
description = ""
authors = ["Sergei Tarassov <starassov@leongaming.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
